### ISSUE TITLE
Inable to load mp3 files.

### ISSUE THREAD

**Issue by Kolia2503** [aheidt/dtw-app#1]
Hello, and thank you very much for providing us this tool!
I installed all the requirements, installed FFMpeg, loaded tha app.py, and I'm able load MIDI files.

But when I want to load any .mp3 or .wav file (from MIDI or original sound), I get always this error:

Loading mp3 file...
Computing chroma features...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Kolia\Desktop\midi\dtw-app-main\app.py", line 406, in on_open_mp3_original
    self.app.data_3.load_chroma_features()
  File "C:\Users\Kolia\Desktop\midi\dtw-app-main\app.py", line 1323, in load_chroma_features
    harm = librosa.effects.harmonic(y=self.app.data_1.y, margin=8)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\librosa\effects.py", line 141, in harmonic
    stft = core.stft(y)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\librosa\core\spectrum.py", line 234, in stft
    y_frames = util.frame(y, frame_length=n_fft, hop_length=hop_length)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\librosa\util\utils.py", line 196, in frame
    xw = as_strided(
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\lib\stride_tricks.py", line 104, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

Whan origin can it come from please?

Kind regards,

**Comment by Kolia2503** [comment]
So, by saving my project, I managed to load all the files when I loaded the project...

Now, I tried the DTW algorithm and got this time this error:

Computing DTW...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Kolia\Desktop\midi\dtw-app-main\app.py", line 517, in apply_dtw_algo
    self.app.dtw_obj.compute_dtw()
  File "C:\Users\Kolia\Desktop\midi\dtw-app-main\dtw.py", line 73, in compute_dtw
    C_FMP = libfmp.c3.compute_cost_matrix(self.x_chroma, self.y_chroma, 'euclidean')
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\libfmp\c3\c3s2_dtw.py", line 27, in compute_cost_matrix
    C = scipy.spatial.distance.cdist(X.T, Y.T, metric=metric)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python38-32\lib\site-packages\scipy\spatial\distance.py", line 2947, in cdist
    return cdist_fn(XA, XB, out=out, **kwargs)
ValueError: Unsupported dtype object

**Comment by aheidt** [comment]
Does loading a shorter .mp3 file still produce this error? e.g. 5 seconds

**Comment by aheidt** [comment]
And another thing, do you have 32 or 64 bit python installed? Apparently using the 32 bit version may cause some issues with numpy.

**Comment by Kolia2503** [comment]
Thank you for your reply.

Yes my bad, it's the 32 bits one...

I have already tried with 30 sec audio file, without result.

But good idea, I tried with 5 sec files, and I was able to load them, apply DTW algorithm, and to export the midi!

**Comment by aheidt** [comment]
Awesome! Let me know if loading longer audio files with 64 bit python works:) It should be able to handle 3min tracks easily

**Comment by Kolia2503** [comment]
I installed Python 64 bits and that solved my problem.

Thank you very much!
